#index:
#    path: /
#    controller: App\Controller\DefaultController::index
save_pdf:
  path: /contract/save-pdf/{contractId}
  controller: App\Controller\ContractController::savePDF
validate_pdf:
  path: /contract/validate-pdf/{contractId}
  controller: App\Controller\ContractController::validatePDF
send_pdf:
  path: /contract/send-pdf/{contractBase64Id}
  controller : App\Controller\ContractController::sendEmail
contract_pdf:
  path: /contract/contract-pdf/{contractId}
  controller : App\Controller\ContractController::editPDF
upload_work_contract:
  path: /upload-work-contract/{studentId}
  controller : App\Controller\IndexController::uploadWorkContract
view_work_contract:
  path: /view-work-contract/{studentId}
  controller : App\Controller\IndexController::viewWorkContract
my_profil:
  path: /my_profile/{userId}
  controller : App\Controller\IndexController::myProfil
notification_backlog:
  path: /notification/notification-backlog/{userId}
  controller: App\Controller\NotificationController::notificationBacklog